### ISSUE TITLE
Error with token after updating

### ISSUE THREAD

**Issue by garrettfuselier** [bzellman/HACS-WindmillAC#35]
Logger: homeassistant.config_entries
Source: config_entries.py:751
First occurred: September 17, 2025 at 4:26:14 PM (3 occurrences)
Last logged: 10:46:36 AM

Error setting up entry Windmill AC: Device Token for windmillac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/windmillac/__init__.py", line 30, in async_setup_entry
    await hass.config_entries.async_setup_platforms(entry, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

**Comment by garrettfuselier** [comment]
I'm also having issues connecting to the dashboard to double check my token, so maybe it's a Windmill issue?

**Comment by OnoBeachBum** [comment]
I can no longer connect since the update. See the following in the logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/windmillac/__init__.py", line 30, in async_setup_entry
    await hass.config_entries.async_setup_platforms(entry, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?
2025-09-19 05:55:03.420 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'windmillac' sets option flow config_entry explicitly, which is deprecated at custom_components/windmillac/config_flow.py, line 34: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/bzellman/HACS-WindmillAC

**Comment by garrettfuselier** [comment]
I rolled back to the previous version and it works fine.

**Comment by glnces** [comment]
@garrettfuselier how did you roll back?

**Comment by OnoBeachBum** [comment]
I just went to a backup of the older version and copied the files from \custom_components\windmillac over the newer version. Then restarted HA and everything started working again.

**Comment by maguerrieri** [comment]
I'm also working again after rolling back; I did this via creating a fork of this repo and creating a GitHub release pointing at the previous commit (https://github.com/maguerrieri/WindmillAC/releases/tag/working), which HACS apparently requires in order to support rollbacks; I couldn't find an option to just install a particular commit.

@bzellman would you possibly be willing to start tagging/creating releases as you go in case this kind of thing happens again?

**Comment by KK1L** [comment]
#34 and this issue are the same...but y'all probably knew that.

**Comment by bzellman** [comment]
Fixed and validated locally and on my prod instance, but please reopen or ping if still and issue.
